name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "/home/tom/elk-demo/.git" ]; then
              git clone -b main git@github.com:YogaTom/elk-demo.git /home/tom/elk-demo
            else
              cd /home/tom/elk-demo && git pull origin main
            fi

            cd /home/tom/elk-demo
            docker compose down
            docker compose up -d --build

